### ISSUE TITLE
Should the throwing observable bubble up to store.init(err)?

### ISSUE THREAD

**Issue by khoomeister** [groupon/shared-store#8]
```javascript
'use strict';

var SharedStore = require('shared-store');
var rx = require('rx');

var store = new SharedStore({
  temp: 'tmp/config',
  loader: rx.Observable.throw(new Error('This throws!'))
});

store.init(function(error, config) {
  console.log('In init');
  if (error) {
    console.log('Yay, I got an error!');
    console.log(error);
  }
});
```

This is the output:
```
Application crashed with current config. Resetting cache.
Trying to remove cache files []
Cache reset successful.

/Users/chkhoo/khoomeister/shared-store-playground/node_modules/shared-store/node_modules/rx/dist/rx.js:580
    throw e;
          ^
Error: This throws!
    at Object.<anonymous> (/Users/chkhoo/khoomeister/shared-store-playground/index.js:8:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

The exception never makes it to the `init` callback.  Is this a bug or intended behavior?

**Comment by jkrems** [comment]
I would say that's a bug. When someone provides an error handler, they expect all errors to be passed through.
